//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuskokaCamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public string amount { get; set; }
        public string payment_type { get; set; }
    }
}
